name: Docker Image CI

on:
    push:
        branches: ["main"]
    schedule:
        - cron: '0 0 15 * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: Login to Docker Container Registry
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/amd64
                  push: true
                  tags: |
                      davescodemusings/tea-runner:latest
                      ghcr.io/davescodemusings/tea-runner:latest
